### ISSUE TITLE
NoSuchMethodError - Crash After a Purchase

### ISSUE THREAD

**Issue by CityVibes** [Purchasely/Purchasely-Android#5]
App crashing immediately after test subscriptions.

Version: 3.4.0

Stacktrace:
```
 java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Lio/purchasely/ext/PLYPurchaseState;ZLio/purchasely/models/PricingInfo;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;Ljava/lang/String;Ljava/lang/String;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lio/purchasely/models/PLYPurchaseReceipt; or its super classes (declaration of 'io.purchasely.models.PLYPurchaseReceipt' appears in /data/app/~~0iF-KgzYcd3_pxFiIvbXVg==/com.androidApp-XWNteWvNc2xp-ha3LRbSdQ==/base.apk!classes11.dex)
                                                                                                    	at io.purchasely.google.BillingRepository.processPurchases(BillingRepository.kt:21)
                                                                                                    	at io.purchasely.google.BillingRepository.processPurchases$default(BillingRepository.kt:1)
                                                                                                    	at io.purchasely.google.BillingRepository.onPurchasesUpdated(BillingRepository.kt:44)
                                                                                                    	at com.android.billingclient.api.zzn.onReceive(com.android.billingclient:billing@@5.0.0:5)
                                                                                                    	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
                                                                                                    	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by CityVibes** [comment]
Had to add missing `io.purchasely:google-play:3.4.0` dependnecy.
